### ISSUE TITLE
Use enums instead of strings where legal values are defined

### ISSUE THREAD

**Issue by jasonmccampbell** [dermesser/async-google-apis#10]
Hi Lewin,

What are your thoughts on using Rust enums for string-type fields where the JSON specifies enum values? For example, one I have hacked into the generated sheets v4 API code:
```
#[derive(Serialize, Deserialize, Debug, Clone, Display)]
pub enum ResponseValueRenderOption {
    FORMATTED_VALUE,
    UNFORMATTED_VALUE,
    FORMULA,
}
```
Display is from the 'strum' crate.

I realize this would be a breaking API change. If you are interested I'll dig into the generator code and try to send a PR for you to take a look at.

Regards,
Jason

**Comment by dermesser** [comment]
Would you be willing to try the current git head? I've integrated enum generation and serialization in the generate.py script, and sheets, drive, youtube compile, and drive even runs (although that one doesn't use enums too much).

Given my laziness, there are not enough (or no) proper tests, so I'd be happy if you could report that the new code still works :)

**Comment by jasonmccampbell** [comment]
Thanks! That's a big improvement. The changes worked well, though I found enums in parameters were not generated, only ones in properties. I sent a PR with changes that add support for it at least as an example; there may be a cleaner way to do it. 

For an example of a parameter left as a string, search for "append" (with the quotes) in the sheets:v4 api, parameter ResponseValueRenderOption. This remained as String type. It's also an example of where the same type is used in many places. The PR I sent removes the scoping so this type is reused, which I think is safe but I don't know for sure.

**Comment by dermesser** [comment]
Oh, that I must have missed. I will take a look at your PR shortly.

**Comment by dermesser** [comment]
This is now mostly implemented (pending further improvements of course).
