### ISSUE TITLE
Generated Code isn't usable in multi-threaded executors.

### ISSUE THREAD

**Issue by ddboline** [dermesser/async-google-apis#13]
The problem can be solved by just adding `Send + Sync` everywhere there's a `dyn Trait` (this only happens in the definition of Service types and in the Download::do_it method).  I'm cooking up an MR that will add a "multi-thread" feature to the crate in the mean time.  Thanks for all the good work on the crate!

**Comment by ddboline** [comment]
I've opened an MR to fix the problem: https://github.com/dermesser/async-google-apis/pull/14

**Comment by dermesser** [comment]
Thank you for report & fix! This is released as 0.3.0.
