### ISSUE TITLE
sheets:v4 metadataId is int, no as_bytes() method

### ISSUE THREAD

**Issue by jasonmccampbell** [dermesser/async-google-apis#9]
Hi Lewin,

The Sheet v4 API is generally working well. In the generated code there are two compilation errors, both this same issue:
```
let rel_path = format!(
     "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
     spreadsheetId = percent_encode(params.spreadsheet_id.as_bytes(), NON_ALPHANUMERIC),
     metadataId = percent_encode(params.metadata_id.as_bytes(), NON_ALPHANUMERIC)
);
```

Here params.metadata_id is type i32, not String, so there is no as_bytes() method. Inserting .to_string() fixes it.

I looked only briefly at generate.py and didn't see the parameters types obviously available. Is this available somewhere and the right fix? I suppose a Rust-level conversion would work as well. Either way, it's a minor issue and the code is working well.

**Comment by dermesser** [comment]
Thank you for reporting this! I will be taking a look shortly.

**Comment by dermesser** [comment]
To my knowledge, ddf224ef4cb447a85ae4caa536f99dff221316e7 fixes this. Can you regenerate and try again from git head?

**Comment by jasonmccampbell** [comment]
Works great! Thanks for the quick fix.
